from .func_demo_ackley import FuncDemoAckley
from .func_demo_alpine import FuncDemoAlpine
from .func_demo_dixon import FuncDemoDixon
from .func_demo_exponential import FuncDemoExponential
from .func_demo_grienwank import FuncDemoGrienwank
from .func_demo_michalewicz import FuncDemoMichalewicz
from .func_demo_piston import FuncDemoPiston
from .func_demo_qing import FuncDemoQing
from .func_demo_rastrigin import FuncDemoRastrigin
from .func_demo_rosenbrock import FuncDemoRosenbrock
from .func_demo_schaffer import FuncDemoSchaffer
from .func_demo_schwefel import FuncDemoSchwefel
